name: Build Zed for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-x86_64-pc-windows-msvc
          override: true

      - name: Install Dependencies
        run: |
          choco install cmake ninja llvm

      - name: Build Zed
        run: cargo run --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zed-windows
          path: target/release/zed.exe
